POST http://localhost:3000/api/v1/brands
Content-Type: application/json

{
  "name": "ClothingClub",
  "commission": 8,
  "registrationNumber": "1111-1234-1234"
}

###

DELETE http://localhost:3000/api/v1/brands/9
