POST http://localhost:3001/api/v1/orders
Content-Type: application/json

{
  "userId": 4,
  "receiverName": "John Doe",
  "receiverPhone": "08123456789",
  "receiverAddress": "Jl. Raya Kebayoran Lama No. 12",
  "orderItems": [
    {
      "productId": 19,
      "productName": "Product 1",
      "productPrice": 1000
    },
    {
      "productId": 20,
      "productName": "Product 2",
      "productPrice": 1000
    }
  ]
}
