POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Product 2",
  "categoryId": 1,
  "brandId": 11,
  "price": 1000,
  "stock": 1
}

###

GET http://localhost:3000/api/v1/products?page=1&limit=10
Content-Type: application/json

###

POST http://localhost:3000/api/v1/products/review
Content-Type: application/json

{
  "productId": 5,
  "userId": 4,
  "comment": "너무 좋아요!!!",
  "rating": 5
}
